---
- name: Créer un utilisateur sur Linux
  hosts: all
  tasks:
    - name: Ensure user bob is present with address information
      win_domain_user:
        name: "{{ name }}"
        firstname: "{{ firstname }}"
        surname: "{{ name }}"
        display_name: "{{ name }} {{ firstname }}"
        password: "{{ password }}"
        state: present
