---
- name: Créer un utilisateur sur Linux
  hosts: "all"
  tasks:
    - name: Add User
      user:
        name: "{{ user }}"
        comment: "{{ user }}"
        password: "{{ password }}"
      no_log: true
