- name: Installation of Iptables
  hosts: all

  tasks:
    - name: Install iptables package
      apt:
        name: iptables
        state: present
      register: result_iptables

    - name: Show result iptables
      debug:
        var: result_iptables

    - name: Already installed Iptables
      debug:
        msg: "Iptables is already installed"
      when: result_iptables.changed == false

    - name: Restart Iptables
      service:
        name: iptables
        state: restarted
      when: result_iptables.changed == true
